# docker-compose.yml
version: '3.7'
services:
  postgres:
    container_name: postgres_container
    image: postgres:12.14
    environment:
      POSTGRES_USER: ${POSTGRES_USER:-postgres}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-Welcome01}
      POSTGRES_DB: ${POSTGRES_DB:-swimtrends}
      PGDATA: /data/postgres
    ports:
      - "5432:5432"
    volumes:
      - swimtrends-pgdata:/data/postgres
#     - ./schema.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - postgres
    restart: unless-stopped

  pgAdmin:
    container_name: pgadmin4_container
    image: dpage/pgadmin4:6.21
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_DEFAULT_EMAIL:-pgadmin4@pgadmin.org}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_DEFAULT_PASSWORD:-admin}
    ports:
      - "${PGADMIN_PORT:-5050}:80"
    volumes:
      - swimtrends-pgadmin:/root/.pgadmin
    networks:
      - postgres
    restart: unless-stopped

networks:
  postgres:
    driver: bridge

volumes:
  swimtrends-pgdata:
  swimtrends-pgadmin:
